trainer:
  init:
    model_dir: /cra-614/workdirs/16072025_data_mix_downstream_testing/model_dir
    seed: 1
    device: CPU
    backend:
      backend_type: CPU
    model:
      name: gpt2
      vocab_size: 54000
      hidden_size: 128
      position_embedding_type: learned
      share_embedding_weights: true
      max_position_embeddings: 2048
      num_hidden_layers: 2
      dropout_rate: 0.0
      layer_norm_epsilon: 1.0e-05
      num_heads: 2
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.0
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      filter_size: 512
      nonlinearity: gelu
      use_ffn_bias: true
      use_bias_in_output: false
      loss_scaling: num_tokens
      loss_weight: 1.0
    callbacks:
    - EleutherEvalHarness:
        eeh_args:
          output_path: /cra-614/workdirs/16072025_data_mix_downstream_testing/model_dir/eval_dir/arc_challenge/checkpoint_2000
          tasks: arc_challenge
          num_fewshot: 0
          log_samples: true
        keep_data_dir: false
        flags:
          csx.performance.micro_batch_size: null
        batch_size: 256
        data_dir: /cra-614/workdirs/16072025_data_mix_downstream_testing/model_dir/downstream_eval_data_arc_challenge
        max_sequence_length: 2048
        tokenizer_file_path: /cra-614/workdirs/16072025_data_mix_downstream_testing/gpt2_tokenizer/neox-20B-tokenizer.json
        eos_id: 50256
        shuffle: false
        num_workers: 1
        pretrained_model_name_or_path: null
    - EleutherEvalHarness:
        eeh_args:
          output_path: /cra-614/workdirs/16072025_data_mix_downstream_testing/model_dir/eval_dir/arc_easy/checkpoint_2000
          tasks: arc_easy
          num_fewshot: 0
          log_samples: true
        keep_data_dir: false
        flags:
          csx.performance.micro_batch_size: null
        batch_size: 256
        data_dir: /cra-614/workdirs/16072025_data_mix_downstream_testing/model_dir/downstream_eval_data_arc_easy
        max_sequence_length: 2048
        tokenizer_file_path: /cra-614/workdirs/16072025_data_mix_downstream_testing/gpt2_tokenizer/neox-20B-tokenizer.json
        eos_id: 50256
        shuffle: false
        num_workers: 1
        pretrained_model_name_or_path: null
    - EleutherEvalHarness:
        eeh_args:
          tasks: mmlu
          num_fewshot: 0
          log_samples: true
          output_path: /cra-614/workdirs/16072025_data_mix_downstream_testing/model_dir/eval_dir/mmlu/checkpoint_2000
        keep_data_dir: false
        flags:
          csx.performance.micro_batch_size: null
        batch_size: 256
        data_dir: /cra-614/workdirs/16072025_data_mix_downstream_testing/model_dir/downstream_eval_data_arc_easy
        max_sequence_length: 2048
        tokenizer_file_path: /cra-614/workdirs/16072025_data_mix_downstream_testing/gpt2_tokenizer/neox-20B-tokenizer.json
        eos_id: 50256
        shuffle: false
        num_workers: 1
        pretrained_model_name_or_path: null
    optimizer:
      AdamW:
        correct_bias: true
        weight_decay: 0.01
        learning_rate: 0.0001
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
    loop:
      max_steps: 2000
      eval_steps: 2
      eval_frequency: 2000
    checkpoint:
      steps: 1000
      strict_version: false
      disable_strict_checkpoint_loading: true
    logging:
      log_steps: 1
    schedulers:
    - SequentialLR:
        schedulers:
        - LinearLR:
            initial_learning_rate: 0.0
            total_iters: 5
            end_learning_rate: 0.0002
        - CosineDecayLR:
            initial_learning_rate: 0.0002
            end_learning_rate: 0
            total_iters: 15
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      mixture:
      - data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/0
        weight: 0.12490010532401141
        data_subset: 0.0000000000000000-1.0
      - data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/1
        weight: 0.09838353641937111
        data_subset: 0.0000000000000000-1.0
      - data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/2
        weight: 0.41405937908793267
        data_subset: 0.0000000000000000-1.0
      - data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/3
        weight: 0.23711483579956028
        data_subset: 0.0000000000000000-1.0
      - data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/4
        weight: 0.12554214336912461
        data_subset: 0.0000000000000000-1.0
      batch_size: 2
      shuffle: true
      shuffle_seed: 1337
      num_workers: 2
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader:
    - data_processor: GptHDF5DataProcessor
      data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/0
      batch_size: 2
      shuffle: false
      num_workers: 2
    - data_processor: GptHDF5DataProcessor
      data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/1
      batch_size: 2
      shuffle: false
      num_workers: 2
    - data_processor: GptHDF5DataProcessor
      data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/2
      batch_size: 2
      shuffle: false
      num_workers: 2
    - data_processor: GptHDF5DataProcessor
      data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/3
      batch_size: 2
      shuffle: false
      num_workers: 2
    - data_processor: GptHDF5DataProcessor
      data_dir: /cra-614/workdirs/11062025_data_mix_expt/temp_datasets/4
      batch_size: 2
      shuffle: false
      num_workers: 2
