trainer:
  init:
    model_dir: ./model_dir
    seed: 1
    device: cpu
    model:
      name: gpt2
      vocab_size: 54000
      hidden_size: 128
      position_embedding_type: learned
      share_embedding_weights: true
      max_position_embeddings: 2048
      num_hidden_layers: 2
      dropout_rate: 0.1
      layer_norm_epsilon: 1.0e-05
      num_heads: 2
      attention_type: scaled_dot_product
      attention_dropout_rate: 0.1
      use_projection_bias_in_attention: true
      use_ffn_bias_in_attention: true
      filter_size: 512
      nonlinearity: gelu
      use_ffn_bias: true
      use_bias_in_output: false
      loss_scaling: num_tokens
      loss_weight: 1.0
    optimizer:
      AdamW:
        correct_bias: true
        weight_decay: 0.01
        learning_rate: 0.0001
    precision:
      enabled: true
      fp16_type: cbfloat16
      loss_scaling_factor: dynamic
    loop:
      max_steps: 50
      eval_frequency: 5
      eval_steps: 1
    checkpoint:
      steps: 5
      strict_version: false
      disable_strict_checkpoint_loading: true
    logging:
      log_steps: 1
    schedulers:
    - ConstantLR:
        learning_rate: 0.0001
  fit:
    train_dataloader:
      data_processor: GptHDF5MapDataProcessor
      mixture:
      - data_dir: /cb/ml/shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/0
        weight: 0.3389001928415014
      - data_dir: /cb/ml/shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/1
        weight: 0.3401436677629992
      - data_dir: /cb/ml/shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/2
        weight: 0.3209561393954994
      batch_size: 2
      shuffle: true
      shuffle_seed: 1337
      num_workers: 8
      prefetch_factor: 10
      persistent_workers: true
    val_dataloader:
    - data_processor: GptHDF5DataProcessor
      data_dir: /cb/ml/shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/7
      batch_size: 2
      shuffle: false
      num_workers: 8
    - data_processor: GptHDF5DataProcessor
      data_dir: /cb/ml/shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/8
      batch_size: 2
      shuffle: false
      num_workers: 8
    - data_processor: GptHDF5DataProcessor
      data_dir: /cb/ml/shuffled/language/datasets/pile_original/hdf5_dataset/train_neox_msl2048/9
      batch_size: 2
      shuffle: false
      num_workers: 8
